FROM python:3.12-slim

WORKDIR /app

ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH=/app

COPY data_pipeline/requirements.ingestion.txt /tmp/requirements.ingestion.txt
RUN pip install --no-cache-dir -r /tmp/requirements.ingestion.txt

COPY data_pipeline /app/data_pipeline

CMD ["python", "-m", "data_pipeline.ingestion.main_ingest"]
