FROM python:3.12-slim

WORKDIR /app

ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH=/app

COPY data_pipeline/requirements.enrichment-non-ml.txt /tmp/requirements.enrichment-non-ml.txt
RUN pip install --no-cache-dir -r /tmp/requirements.enrichment-non-ml.txt

COPY data_pipeline /app/data_pipeline

CMD ["python", "-m", "data_pipeline.enrichment.main_enrich_non_ml"]
